name: Update List
on:
  push:
    branches:
      - src
  schedule:
    - cron: "0 0 * * *"

env:
  WORKFLOW_ACTION: update_list

jobs:
  update_list:
    name: Update List
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Deps
        run: pip install jinja2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Raw List
        run: make fetch_list
      - name: Generate Files
        run: make generate_files
      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: update list" -a
      - name: Push Changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: src
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          force_orphan: true
