name: Update List
on:
  push:
    branches:
      - src
  schedule:
    - cron: "0 0 * * *"

env:
  WORKFLOW_ACTION: update_list

jobs:
  update_list:
    name: Update List
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install Deps
        run: |
          pip install jinja2 graphviz networkx beautifulsoup4 lxml smartypants fonttools brotli
          sudo apt install pdf2svg unzip
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout fonts
        uses: actions/checkout@v2
        with:
          repository: indestructible-type/indestructible-type.github.io
          path: indestructible-type
      - name: Package fonts locally
        run: |
          curl -L https://github.com/alerque/libertinus/releases/download/v6.12/Libertinus-6.12.zip -o libertinus.zip
          unzip libertinus.zip
          for i in Libertinus-6.12/LibertinusSerif*.otf; do
            pyftsubset $i --unicodes="U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD, U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF" --flavor=woff2 --output-file=${i%.*}.woff2
          done
          for i in indestructible-type/fonts/Bodoni/*.otf; do
            fonttools ttLib.woff2 compress $i
          done
          for i in indestructible-type/fonts/Jost*.ttf; do
            fonttools ttLib.woff2 compress $i
          done
          mkdir -p public/fonts
          cp Libertinus-6.12/*.woff2 public/fonts
          cp indestructible-type/fonts/Bodoni/*.woff2 public/fonts
          cp indestructible-type/fonts/*.woff2 public/fonts
          mkdir -p ~/.local/share/fonts
          cp indestructible-type/fonts/Bodoni/Bodoni-11-Medium.otf ~/.local/share/fonts
      - name: Fetch Raw List
        run: make fetch_list
      - name: Generate Files
        run: make generate_files
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          force_orphan: true
