name: Update List
on:
  push:
    branches:
      - src
  schedule:
    - cron: "0 0 * * *"

env:
  WORKFLOW_ACTION: update_list

jobs:
  update_list:
    name: Update List
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install Deps
        run: |
          pip install jinja2 graphviz networkx beautifulsoup4
          sudo apt install pdf2svg woff2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout fonts
        uses: actions/checkout@v2
        with:
          repository: indestructible-type/indestructible-type.github.io
          path: indestructible-type
      - name: Package fonts locally
        run: |
          for i in indestructible-type/fonts/Bodoni/*.otf; do
            woff2_compress $i
          done
          for i in indestructible-type/fonts/Jost*.ttf; do
            woff2_compress $i
          done
          mkdir -p public/fonts
          cp indestructible-type/fonts/Bodoni/*.woff2 public/fonts
          cp indestructible-type/fonts/*.woff2 public/fonts
          mkdir -p ~/.local/share/fonts
          cp indestructible-type/fonts/Bodoni/Bodoni-11-Medium.otf ~/.local/share/fonts
      - name: Fetch Raw List
        run: make fetch_list
      - name: Generate Files
        run: make generate_files
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          force_orphan: true
